using System;
using System.Collections.Generic;

namespace eMistrApiScaffold.Models
{
    public partial class COrder
    {
        public ulong Id { get; set; }
        public string BarId { get; set; }
        public string Name { get; set; }
        public ulong ParentId { get; set; }
        public string Code { get; set; }
        public ulong CustomerId { get; set; }
        public string Note { get; set; }
        public DateTime Start { get; set; }
        public DateTime Finish { get; set; }
        public string CustomerName { get; set; }
        public string Active { get; set; }
        public int UserTime { get; set; }
        public decimal UserPrice { get; set; }
        public string User { get; set; }
        public int Typ { get; set; }
        public int RealTime { get; set; }
        public decimal RealPrice { get; set; }
        public string Created { get; set; }
        public decimal Kusu { get; set; }
        public ulong LastOp { get; set; }
        public string Drawing { get; set; }
        public string Note2 { get; set; }
        public string CisloObjednavky { get; set; }
        public int HasDocs { get; set; }
        public DateTime MontazDate { get; set; }
        public int MontazTime { get; set; }
        public ulong CreatedMatId { get; set; }
        public decimal Prevedeno { get; set; }
        public decimal Expandovano { get; set; }
        public ulong IntBarId { get; set; }
        public decimal OkenUnit { get; set; }
        public int UserTimeOrder { get; set; }
        public int VypoctenoVyrobeno { get; set; }
        public int UserTimeKsSecond { get; set; }
        public string NoteNabidka { get; set; }
        public decimal PriceUkony { get; set; }
        public string Volitelna1 { get; set; }
        public string Volitelna2 { get; set; }
        public string Volitelna3 { get; set; }
        public string Volitelna4 { get; set; }
        public string Volitelna5 { get; set; }
        public string Volitelna6 { get; set; }
        public string Volitelna7 { get; set; }
        public string Volitelna8 { get; set; }
        public string Volitelna9 { get; set; }
        public string Volitelna10 { get; set; }
        public string Volitelna11 { get; set; }
        public string Volitelna12 { get; set; }
        public int PocetKlt { get; set; }
        public decimal UserPriceMat { get; set; }
        public decimal UserPriceSub { get; set; }
        public decimal UserPriceWork { get; set; }
        public decimal Ukon1Planks { get; set; }
        public decimal Ukon2Planks { get; set; }
        public decimal Ukon3Planks { get; set; }
        public decimal Ukon4Planks { get; set; }
        public decimal Ukon5Planks { get; set; }
        public decimal Ukon6Planks { get; set; }
        public decimal Ukon7Planks { get; set; }
        public decimal Ukon8Planks { get; set; }
        public decimal Ukon9Planks { get; set; }
        public decimal Ukon10Planks { get; set; }
        public decimal Ukon11Planks { get; set; }
        public decimal Ukon12Planks { get; set; }
        public decimal Ukon13Planks { get; set; }
        public decimal Ukon14Planks { get; set; }
        public decimal Ukon15Planks { get; set; }
        public decimal Ukon1Vyrobenoks { get; set; }
        public decimal Ukon2Vyrobenoks { get; set; }
        public decimal Ukon3Vyrobenoks { get; set; }
        public decimal Ukon4Vyrobenoks { get; set; }
        public decimal Ukon5Vyrobenoks { get; set; }
        public decimal Ukon6Vyrobenoks { get; set; }
        public decimal Ukon7Vyrobenoks { get; set; }
        public decimal Ukon8Vyrobenoks { get; set; }
        public decimal Ukon9Vyrobenoks { get; set; }
        public decimal Ukon10Vyrobenoks { get; set; }
        public decimal Ukon11Vyrobenoks { get; set; }
        public decimal Ukon12Vyrobenoks { get; set; }
        public decimal Ukon13Vyrobenoks { get; set; }
        public decimal Ukon14Vyrobenoks { get; set; }
        public decimal Ukon15Vyrobenoks { get; set; }
        public int Priorita { get; set; }
        public string Volitelna13 { get; set; }
        public int PlanKalendar { get; set; }
        public string ExterniId { get; set; }
        public ulong TechpostupId { get; set; }
        public decimal CiselnaVolitelna1 { get; set; }
        public decimal CiselnaVolitelna2 { get; set; }
        public string Unirec { get; set; }
        public string Volitelna14 { get; set; }
        public DateTime Datumcaszmeny { get; set; }
        public DateTime DatumovaVolitelna1 { get; set; }
        public DateTime DatumovaVolitelna2 { get; set; }
        public DateTime DatumovaVolitelna3 { get; set; }
        public DateTime DatumovaVolitelna4 { get; set; }
        public decimal KoeficientOn { get; set; }
        public decimal OdmenyPredpoklad { get; set; }
        public decimal OdmenyVyuctovano { get; set; }
        public string ExterniFaktura { get; set; }
        public int? VykresZeSouboru { get; set; }
        public DateTime DatumExpedice { get; set; }
        public ulong ZpusobDopravyId { get; set; }
        public int Baliku1 { get; set; }
        public int Baliku2 { get; set; }
        public int Baliku3 { get; set; }
        public int EmailUpozornovat { get; set; }
        public int SkladGroupId { get; set; }
        public int OperationGroupId { get; set; }
        public string DispTree { get; set; }
        public int Uroven { get; set; }
        public int MasterOrderId { get; set; }
        public int CustomerIdAdresa { get; set; }
        public decimal CiselnaVolitelna3 { get; set; }
        public string IdPohoda { get; set; }
        public DateTime StartVyroba { get; set; }
        public DateTime FinishVyroba { get; set; }
        public int Viceprace { get; set; }
        public int Unit { get; set; }
        public decimal Rozmer1 { get; set; }
        public decimal Rozmer2 { get; set; }
        public decimal Rozmer3 { get; set; }
        public decimal OrderCenaJednotka { get; set; }
        public decimal CiselnaVolitelna4 { get; set; }
        public string Volitelna15 { get; set; }
        public string Volitelna16 { get; set; }
        public int TypVypoctuCeny { get; set; }
        public decimal RealPrice2 { get; set; }
        public int GdprZbyva { get; set; }
        public int GdprAnonymizovano { get; set; }
        public string DruhaMenaZkratka { get; set; }
        public decimal RealMzda { get; set; }
        public int ForcePrepocet { get; set; }
        public int IdCiselnaRada { get; set; }
        public string PrefixCiselnaRada { get; set; }
        public int IsSablona { get; set; }
        public decimal CiselnaVolitelna5 { get; set; }
        public decimal CiselnaVolitelna6 { get; set; }
        public DateTime TsLastChange { get; set; }
        public DateTime TsCreated { get; set; }
    }
}
