using System;
using System.Collections.Generic;

namespace eMistrApiScaffold.Models
{
    public partial class GlobalSettings
    {
        public int Id { get; set; }
        public int VyberPrijemky { get; set; }
        public int KomentarDoPredpokladmat { get; set; }
        public int UkonyKomentarUkonu { get; set; }
        public string SlozkaFotky { get; set; }
        public int UseImportmoney { get; set; }
        public string SlozkaMoney { get; set; }
        public string InitdirSkladmatedit { get; set; }
        public string InitdirPrijemka { get; set; }
        public string InitdirDokument { get; set; }
        public int NazevprijemkyDleSouboru { get; set; }
        public string OrderCiselnavolitelna1Popis { get; set; }
        public string OrderCiselnavolitelna2Popis { get; set; }
        public string WcPauzaBarid { get; set; }
        public int WcPauzaLimit { get; set; }
        public int ZakazkyKodNazev { get; set; }
        public int VyskladnovatSPevnouCenou { get; set; }
        public int DefaultniMarze { get; set; }
        public int DochazkaTyp { get; set; }
        public int DochazkaZaokrouhlovatNa { get; set; }
        public int DochazkaSumyVeDnech { get; set; }
        public int DochazkaRozpoznavatSmeny { get; set; }
        public int ZauctovanoZakazkyStav { get; set; }
        public int MoneyVychoziStavId { get; set; }
        public int VychoziTypCenyUkonu { get; set; }
        public int ZakBezMarze { get; set; }
        public int UsersColumns { get; set; }
        public int FakturaZakazkyStav1 { get; set; }
        public int FakturaZakazkyStav2 { get; set; }
        public int ProbihaKlon { get; set; }
        public int DelitDochazku { get; set; }
        public string PrintPodpis { get; set; }
        public int UseDph { get; set; }
        public int OnePrijmForObj { get; set; }
        public int EdtSmrFromOrd { get; set; }
        public int OrdInsNonsklad { get; set; }
        public int OrdSumUprice { get; set; }
        public string OcrBarId { get; set; }
        public int OrdOnlyWorkDayLeft { get; set; }
        public int DefPayFak { get; set; }
        public string FrExportdir { get; set; }
        public int FrSavestyl { get; set; }
        public int OrdIqFiltrRd { get; set; }
        public int DochNoComm { get; set; }
        public int DochBreakRound { get; set; }
        public string DochBreakBarId { get; set; }
        public int LckTimeUse { get; set; }
        public int OrdShowKoop { get; set; }
        public int DochSpecPrescas { get; set; }
        public int PrijmNochEditPrice { get; set; }
        public bool WebServicePinAuth { get; set; }
        public int VychoziStavZakazky { get; set; }
        public int PrijmSilCtecka { get; set; }
        public int OrdUspora { get; set; }
        public int DochNeukBack { get; set; }
        public int DefaultUnit { get; set; }
        public int CazerSkladId { get; set; }
        public int UseFastreport { get; set; }
        public int GrafickyprehledRefresh { get; set; }
        public int ZobrazitCelySklad { get; set; }
        public int ImportExt { get; set; }
        public string ImportExtCaption { get; set; }
        public string ImportExtExec { get; set; }
        public string ImportExtParams { get; set; }
        public int AktualniStavNovy { get; set; }
        public ulong KontrolaMnozstvi { get; set; }
        public int KontrolaMnozstviOperaceTyp { get; set; }
        public int KontrolaMnozstviOperacePrekroceni { get; set; }
        public ulong KontrolaMnozstviNesmiPrekrocitZakazku { get; set; }
        public decimal KontrolaMnozstviOperaceHodnota { get; set; }
        public string UrlPrefixImage { get; set; }
        public int ObjednavkyPrijateEnabled { get; set; }
        public int EfektivitaOrderWork { get; set; }
        public int LimitZaznamu { get; set; }
        public int LimitZaznamuPocet { get; set; }
        public int StavZasobDoMinusu { get; set; }
        public int ZobrazovatDetailAdres { get; set; }
        public int ZobrazovatZbyvajiciCasReaddata { get; set; }
        public string PlacVolnoBarId { get; set; }
        public int CazerSkladPct { get; set; }
        public string VychoziJazyk { get; set; }
        public int OrderWorkPripravaVypocet { get; set; }
        public string UrlIntranet { get; set; }
        public int CazerSkladPctMontaz { get; set; }
        public int CazerSkladPctSprava { get; set; }
        public int OrderworkNovePoradi { get; set; }
        public int OrderworkDeleteUsed { get; set; }
        public int OrderDokoncenoProcentKusy { get; set; }
        public string CasDefSkladGroupDily { get; set; }
        public string DochAbsenceBarId { get; set; }
        public int OperationPctUp { get; set; }
        public string OrderCiselnavolitelna3Popis { get; set; }
        public DateTime CasKlon { get; set; }
        public int DlPocitatMnozstvi { get; set; }
        public int DlVytvoritVydejku { get; set; }
        public int DlPocitatMnozstviFrom { get; set; }
        public int OwVicenasobnePoradi { get; set; }
        public int OwVicenasobneOnlyFirst { get; set; }
        public int KoeficientyDleSkupin { get; set; }
        public int CreateDirOrder { get; set; }
        public string CreateDirOrderPath { get; set; }
        public string OrderCiselnavolitelna4Popis { get; set; }
        public int ImportExtDl { get; set; }
        public string ImportExtDlCaption { get; set; }
        public string ImportExtDlExec { get; set; }
        public string ImportExtDlParams { get; set; }
        public int OrderEditCalc { get; set; }
        public string OrderEditCalcFunctionName { get; set; }
        public string OrderEditCalcScript { get; set; }
        public int OrderPodzakazkaSufixFromDefault { get; set; }
        public int DlCastecneVydaneDoPodzakazky { get; set; }
        public int OrderButtonSaveRecalculate { get; set; }
        public int PrintworkerSkupinyChange { get; set; }
        public int ObjednavkyNeseskupovatMaterial { get; set; }
        public int ObjednavkyPrebiratZakazku { get; set; }
        public int CreateSubdirOrder { get; set; }
        public string CreateSubdirOrderPath { get; set; }
        public int Newcolumnselector { get; set; }
        public int Orderstavdirectorychange { get; set; }
        public string Orderstavdirectorychangepath { get; set; }
        public int Orderstavdirectorychangeactive { get; set; }
        public int Skladpouzitvychozipohyby { get; set; }
        public int SkladpouzitvychozipohybyPrijemka { get; set; }
        public int SkladpouzitvychozipohybyVydejka { get; set; }
        public int Usetisktable { get; set; }
        public int OrderworkNeprepocitavatPoradi { get; set; }
        public int OrderSablonaVolitelnePolozky { get; set; }
        public int OrderSablonaTypZakazky { get; set; }
        public int OrderSablonaCasMontaze { get; set; }
        public int OrderSablonaKomentarObchodni { get; set; }
        public int OrderSablonaRozmery { get; set; }
        public int OrderWorkEditCalc { get; set; }
        public string OrderWorkEditCalcFunctionName { get; set; }
        public string OrderWorkEditCalcScript { get; set; }
        public int NaskladnenoZakazkyStav { get; set; }
        public int TypVypoctuCeny { get; set; }
        public int NovaUkolMzda { get; set; }
        public int OrderPrijemFinalVyrobek { get; set; }
        public string OrderKlonText { get; set; }
        public int SkladMaterialCenaCelkemTyp { get; set; }
        public int MainFormButtonsShow { get; set; }
        public int OrdInsNonskladTyp { get; set; }
        public string DefaultMena { get; set; }
        public string MenaZkratka { get; set; }
        public int CiziMena { get; set; }
        public int SkladMaterialVratkaPohyb { get; set; }
        public int DlCheckOrderBaridInCode { get; set; }
        public int DlZauctovanoZakazkyStav { get; set; }
        public int ObjednavkySubdodavkyDatum { get; set; }
        public int ObjednavkySubdodavkyCena { get; set; }
        public int DlVytvorenoZakazkyStav { get; set; }
        public int UseStavyDokladu { get; set; }
        public int UseSkladovePozice { get; set; }
        public int UseSkladoveSkupinyBatchOut { get; set; }
        public int CreateSubdirOrderAddName { get; set; }
        public int SkladRozpadMaterialuShow { get; set; }
        public decimal WorkerKoeficientDefault { get; set; }
        public decimal WorkerMzdaDefault { get; set; }
        public int OrdereditTypVypoctuVisible { get; set; }
        public int OrderKlonAllOperationPlanned { get; set; }
        public int Newsqllike { get; set; }
        public int Ordercallintranet { get; set; }
        public string OrdercallintranetUrl { get; set; }
        public int Filterreplacecomma { get; set; }
        public decimal CncCenaDefault { get; set; }
        public int OrderSablonaObjednavky { get; set; }
        public int WorkerUseKoeficient2 { get; set; }
        public int SkladMaterialDodavateleShow { get; set; }
        public int SkladMaterialInventuryShow { get; set; }
        public string OrderCiselnavolitelna5Popis { get; set; }
        public int OrderGridCenyCasy { get; set; }
        public int OperationUsercodeEnabled { get; set; }
        public string OrderCiselnavolitelna6Popis { get; set; }
        public int OrderSubdodavkaPrebiratPocetMj { get; set; }
        public int OrderworkNewPoradiEnabled { get; set; }
        public int RightPanelShowPozice { get; set; }
        public int PriceCalculate { get; set; }
        public string OrderRozdelDefskupinastavu { get; set; }
    }
}
